### getPost
# Get post by ID
GET http://localhost:3332/api/post/10 HTTP/1.1

### getPosts
# Get all posts
GET http://localhost:3332/api/post HTTP/1.1

### deletePost
# Delete post by ID
DELETE http://localhost:3332/api/post/8 HTTP/1.1
Authorization: Bearer {{jwt_token}}

### createTextPost
# Create a new text post
POST http://localhost:3332/api/post/new HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "type": "ext",
  "status": "posted",
  "title": "4yuguiyhpuihphpuihphpuhpuihpu",
  "announcement": "yuguiyhpuihphpuihphpuhpuihpuyuguiyhpuihphpuihphpuhpuihpuyuguiyhpuihphpuihphpuhpuihpu",
  "description": "D",
  "text": "heyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheyaheya",
  "tags": ["AAAaaa", "aaaaaa", "BbBbBb"]
}

### updateTextPost
# Update a text post
PATCH http://localhost:3332/api/post/8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "text": "heyaaaaaaaaaaaddddaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}

### createImagePost
# Create a new image post
POST http://localhost:3332/api/post/new HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "type": "image",
  "title": "UUU",
  "imageLink": "https://www.okok.com/feed/img.png",
  "tags": ["jjjjiee", "pppppp"]
}

### createVideoPost
# Create a new video post
POST http://localhost:3332/api/post/new HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "type": "video",
  "title": "TTTTTTTTTTTTTTTTTTTTTTTTTTT",
  "videoLink": "https://youtu.be/bbbbbbbbbbb",
  "tags": ["p3ppppp", "gggdj", "pppppp", "gg1j", "apppppp"]
}

### repost
# Like/dislike a post
POST http://localhost:3332/api/post/9/repost HTTP/1.1
Authorization: Bearer {{jwt_token}}

### likePost
# Like/dislike a post
POST http://localhost:3332/api/post/8/like?action=1 HTTP/1.1
Authorization: Bearer {{jwt_token}}

### sendNewsletters
# Send email newsletter about new posts
POST http://localhost:3332/api/post/news HTTP/1.1
Authorization: Bearer {{jwt_token}}

### getPostsByUserIds
# Get posts from users
POST http://localhost:3332/api/post/by-users HTTP/1.1
Content-Type: application/json

{
  "ids": ["6451194059bccfdfae38ef17"]
}
