# Get post by ID
GET http://localhost:3333/api/post/e7565eea-ab34-474f-ab1a-4db36aeaf037 HTTP/1.1

###

# Delete post by ID
DELETE http://localhost:3333/api/post/e7565eea-ab34-474f-ab1a-4db36aeaf037 HTTP/1.1

###

# Create a new text post
POST http://localhost:3333/api/post/new HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "status": "draft",
  "title": "TITLE",
  "announcement": "ANNOUNCEMENT",
  "description": "DESCRIPTION",
  "text": "heya",
  "tags": ["hello", "bye"]
}

###

# Update a text post
PATCH http://localhost:3333/api/post/6ee28734-4e16-4027-8351-f76022bba3b8 HTTP/1.1
Content-Type: application/json

{
  "text": "heya2"
}

###

# Create a new image post
POST http://localhost:3333/api/post/new HTTP/1.1
Content-Type: application/json

{
  "type": "image",
  "status": "posted",
  "title": "TITLE",
  "imageLink": "IMAGELINK",
  "tags": ["hello", "bye"]
}

###
