# Create a new text post
POST http://localhost:3333/api/post/new HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "status": "draft",
  "title": "TITLE",
  "announcement": "ANNOUNCEMENT",
  "description": "DESCRIPTION",
  "text": "heya",
  "tags": ["hello", "bye"]
}

###

# Get post by ID
GET http://localhost:3333/api/post/8a4da666-31e6-458b-92ef-54d870582e3a HTTP/1.1

###

# Update post
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
 "email": "user@notfound.local",
 "password": "123456"
}

###
