### loginUser
# Login user by email and password

POST http://localhost:3500/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "keksissimo@mail.com",
  "password": "123456"
}

> {%
  client.global.set("jwt_token", response.body.accessToken);
  client.global.set("refresh_jwt_token", response.body.refreshToken)
%}

### createUser
# Create a new user

POST http://localhost:3500/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "keksissimo@mail.com",
  "avatar": "avt.png",
  "name": "Keks",
  "password": "123456"
}

### getUser
# Get user by ID

GET http://localhost:3500/api/auth/6442815b2ef0e2b10f8b775f HTTP/1.1
Authorization: Bearer {{jwt_token}}

### refresh
# Get new JWT pair
POST http://localhost:3500/api/auth/refresh HTTP/1.1
Authorization: Bearer {{refresh_jwt_token}}
