# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
 "email": "keksissimo@mail.com",
 "avatar": "avt.png",
 "name": "Keks",
 "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/643b0353a7a73633372a89c6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDNiMDM1M2E3YTczNjMzMzcyYTg5YzYiLCJlbWFpbCI6Imtla3Npc3NpbW9AbWFpbC5jb20iLCJuYW1lIjoiS2VrcyIsImlhdCI6MTY4MTU4OTA5OCwiZXhwIjoxNjgxNTkyNjk4fQ.6ICMLbwJWE2WjOmNMX5qFwJDnpOzE-A61B4psLMx7Wk


###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
 "email": "keksissimo@mail.com",
 "password": "123456"
}

###
