# Create a new user
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
 "email": "user@notfound.local",
 "avatar": "avt.png",
 "name": "Keks",
 "password": "123456"
}

###

# Get user by ID
GET http://localhost:3333/api/auth/e3d04011-a093-4f50-9203-03660e6f02cc HTTP/1.1

###

# Login user by email and password
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
 "email": "user@notfound.local",
 "password": "123456"
}

###
