### getCommentsByPostId
# Get comments by post ID
GET http://localhost:3332/api/comment/post/10 HTTP/1.1

### createComment
# Create a new comment for post
POST http://localhost:3332/api/comment/new HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "postId": 10,
  "text": "HOLYYYMOLYYY"
}

### deleteComment
# Delete a single comment
DELETE http://localhost:3332/api/comment/3 HTTP/1.1
Authorization: Bearer {{jwt_token}}

